version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: ask-me-anything-db
    ports:
      - '5432:5432'
    environment:
      POSTGRESQL_USERNAME: ${DATABASE_USERNAME}
      POSTGRESQL_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRESQL_POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRESQL_DATABASE: ${DATABASE_NAME}
    volumes:
      - postgres_data:/bitnami/postgresql
  
  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   depends_on:
  #     - postgres
  #   ports:
  #     - 8081:80
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: password
  #   volumes:
  #     - pgadmin:/var/lib/pgadmin

volumes:
  postgres_data:
  # pgadmin: